---
abstract: 'Moose exception class composed from traits'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Test::More: 0.74
configure_requires:
  Module::Build: 0.38
  version: 0.77
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unexpected
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Unexpected:
    file: lib/Unexpected.pm
    version: v0.1.10
  Unexpected::TraitFor::ErrorLeader:
    file: lib/Unexpected/TraitFor/ErrorLeader.pm
    version: v0.1.8
  Unexpected::TraitFor::StringifyingError:
    file: lib/Unexpected/TraitFor/StringifyingError.pm
    version: v0.1.8
  Unexpected::TraitFor::Throwing:
    file: lib/Unexpected/TraitFor/Throwing.pm
    version: v0.1.2
  Unexpected::TraitFor::TracingStacks:
    file: lib/Unexpected/TraitFor/TracingStacks.pm
    version: v0.1.2
requires:
  Carp: 0
  Devel::StackTrace: 1.26
  List::Util: 1.27
  Moose: 2.0802
  MooseX::ClassAttribute: 0.27
  MooseX::Role::WithOverloading: 0.13
  MooseX::Types: 0.35
  MooseX::Types::Common: 0.001008
  MooseX::Types::LoadableClass: 0.008
  Scalar::Util: 1.27
  namespace::autoclean: 0.13
  overload: 1.07
  perl: 5.01
  version: 0.88
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Unexpected
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.1.10
