---
abstract: 'Exception class composed from traits'
author:
  - 'Peter Flanigan <pjfl@cpan.org>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unexpected
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Unexpected:
    file: lib/Unexpected.pm
    version: v0.7.1
  Unexpected::Functions:
    file: lib/Unexpected/Functions.pm
    version: v0.7.1
  Unexpected::TraitFor::ErrorLeader:
    file: lib/Unexpected/TraitFor/ErrorLeader.pm
    version: v0.7.1
  Unexpected::TraitFor::StringifyingError:
    file: lib/Unexpected/TraitFor/StringifyingError.pm
    version: v0.7.1
  Unexpected::TraitFor::Throwing:
    file: lib/Unexpected/TraitFor/Throwing.pm
    version: v0.7.1
  Unexpected::TraitFor::TracingStacks:
    file: lib/Unexpected/TraitFor/TracingStacks.pm
    version: v0.7.1
  Unexpected::Types:
    file: lib/Unexpected/Types.pm
    version: v0.7.1
requires:
  Class::Usul: v0.22.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Unexpected
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.7.1
