---
abstract: 'Exception class composed from traits'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unexpected
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Unexpected:
    file: lib/Unexpected.pm
    version: v0.2.1
  Unexpected::TraitFor::ErrorLeader:
    file: lib/Unexpected/TraitFor/ErrorLeader.pm
    version: v0.2.1
  Unexpected::TraitFor::StringifyingError:
    file: lib/Unexpected/TraitFor/StringifyingError.pm
    version: v0.2.1
  Unexpected::TraitFor::Throwing:
    file: lib/Unexpected/TraitFor/Throwing.pm
    version: v0.2.1
  Unexpected::TraitFor::TracingStacks:
    file: lib/Unexpected/TraitFor/TracingStacks.pm
    version: v0.2.1
  Unexpected::Types:
    file: lib/Unexpected/Types.pm
    version: v0.2.1
recommends:
  App::cpanminus: 1.6005
requires:
  Class::Load: 0.18
  Devel::StackTrace: 1.26
  Moo: 1.002
  Type::Tiny: 0.006
  namespace::clean: 0.23
  namespace::sweep: 0.006
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Unexpected
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.2.1
