---
abstract: 'Exception class composed from traits'
author:
  - 'Peter Flanigan, C<< <pjfl@cpan.org> >>'
build_requires:
  Module::Build: '0.4004'
  Test::Requires: '0.06'
  Try::Tiny: '0.18'
  version: '0.88'
configure_requires:
  Module::Build: '0.4004'
  version: '0.88'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Unexpected
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Unexpected:
    file: lib/Unexpected.pm
    version: v0.26.1
  Unexpected::Functions:
    file: lib/Unexpected/Functions.pm
    version: v0.26.1
  Unexpected::TraitFor::ErrorLeader:
    file: lib/Unexpected/TraitFor/ErrorLeader.pm
    version: v0.26.1
  Unexpected::TraitFor::ExceptionClasses:
    file: lib/Unexpected/TraitFor/ExceptionClasses.pm
    version: v0.26.1
  Unexpected::TraitFor::StringifyingError:
    file: lib/Unexpected/TraitFor/StringifyingError.pm
    version: v0.26.1
  Unexpected::TraitFor::Throwing:
    file: lib/Unexpected/TraitFor/Throwing.pm
    version: v0.26.1
  Unexpected::TraitFor::TracingStacks:
    file: lib/Unexpected/TraitFor/TracingStacks.pm
    version: v0.26.1
  Unexpected::Types:
    file: lib/Unexpected/Types.pm
    version: v0.26.1
requires:
  Devel::StackTrace: '1.26'
  Exporter::Tiny: '0.038'
  Module::Runtime: '0.014'
  Moo: '1.005000'
  Package::Stash: '0.36'
  Sub::Install: '0.928'
  Type::Tiny: '>= 0.042, != 0.44'
  namespace::autoclean: '0.19'
  namespace::clean: '0.25'
  perl: '5.010001'
  strictures: '1.005004'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Unexpected
  homepage: https://metacpan.org/author/PJFL
  license: http://dev.perl.org/licenses/
version: 0.26.1
